name: Build and Push to ECR
 
on:

  push:

    branches:

      - main   # or whichever branch should trigger
 
jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v3
 
      - name: Configure AWS credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ${{ secrets.AWS_REGION }}
 
      - name: Login to ECR

        uses: aws-actions/amazon-ecr-login@v2
 
      - name: Build Docker image

        run: |

          docker build -t ${{ secrets.ECR_REPO_URI }}:latest .
 
      - name: Push to ECR

        run: |

          docker push ${{ secrets.ECR_REPO_URI }}:latest
 
