name: Build & Push Frontend to ECR
 
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Frontend
        run: |
          FRONTEND_REPO="${{ steps.login-ecr.outputs.registry }}/kiran-weisley-frontend"
          docker build -t $FRONTEND_REPO:latest ./frontend
          docker push $FRONTEND_REPO:latest

