name: kiran-wesley-sample CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/kiran-frontend-deploy.yml'

env:
  IMAGE: kiran-frontend
  REGISTRY_HOSTNAME: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      docker_tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_HOSTNAME }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}
          tags: |
            type=sha

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy kiran Frontend to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --parameters 'commands=[
              "export DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}",
              "export DOCKER_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}",
              "export TAG=${{ needs.build-and-push.outputs.docker_tag }}",
              "echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_USERNAME --password-stdin || exit 1",
              "docker pull docker.io/$DOCKER_USERNAME/kiran-frontend:$TAG || exit 1",
              "docker stop kiran-frontend-container || true",
              "docker rm kiran-frontend-container || true",
              "docker run -d --name kiran-frontend-container -p 4173:4173 --env-file /home/ubuntu/env/kiran-weisley.env docker.io/$DOCKER_USERNAME/kiran-frontend:$TAG || exit 1",
              "docker image prune -af || true",
              "docker system prune -af --volumes || true"
            ]' \
            --comment "Deploying kiran-wesley-sample Frontend via GitHub Actions (SHA tag)" \
            --region ap-south-1 \
            --output text
